# Generated by Django 5.2.5 on 2025-08-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fdc_id", models.IntegerField()),
                ("description", models.CharField(max_length=255)),
                ("nutrient_id", models.IntegerField()),
                ("nutrient_name", models.CharField(max_length=255)),
                ("amount_per_100g", models.FloatField()),
                ("unit", models.CharField(max_length=50)),
            ],
        ),
    ]
